  name: sensorbox${id}
  friendly_name: Sensorbox ${id} - ${location}
  temp_hot: "24"
  temp_cold: "18"
  dry_high: "10"
  dry_medium: "20"
  dry_low: "30"
  humid_low: "45"
  humid_medium: "55"
  humid_high: "60"
  co2_low: "1000"
  co2_medium: "1500"
  co2_high: "2000"
  voc_low: "100"
  voc_medium: "200"
  voc_high: "400"
  ch2o_low: "30"
  ch2o_medium: "40"
  ch2o_high: "50"
  pm1_low: "5"
  pm1_medium: "15"
  pm1_high: "25"
  pm25_low: "5"
  pm25_medium: "15"
  pm25_high: "25"
  pm40_low: "5"
  pm40_medium: "15"
  pm40_high: "25"
  pm10_low: "5"
  pm10_medium: "15"
  pm10_high: "25"
  wifi_icon: "\U000F05A9"
  no_wifi_icon: "\U000F16BC"
  ha_icon: "\U000F07D0"
  no_ha_icon: "\U000F087B"
  co2_str: "CO\u2082"
  ch2o_str: "CH\u2082O"
  ug_m3_str: "µg/m³"
  deg_c_str: "°C"
  deg_f_str: "°F"
  hot_hex: "FF0000"
  comfort_hex: "FFFFFF"
  cold_hex: "0000FF"
  high_hex: "FF0000"
  medium_hex: "FFa500"
  low_hex: "FFFF00"
  safe_hex: "FFFFFF"
  error_hex: "8A2BE2"
